version: "3.8"

services:
  web:
    build: .
    container_name: financial-alert-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:alpine
    container_name: crypto-redis
    ports:
      - "6379:6379"


  celery-worker:
    build: .
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A app.celery_app worker --loglevel=info


  celery-beat:
    build: .
    environment: 
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    command: celery -A app.celery_app beat --loglevel=info
