name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/acheckout@v2
      - name:  Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependecies
        run: pip install requests
      - name: Run tests
        run: python test_simple.py


